# Generated by Django 3.2.9 on 2021-11-23 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
    ]
